---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8787, host: 8787}]
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: centos-7.1
  - name: amazon
    driver:
      username: ec2-user

suites:
  - name: default
    run_list:

      - recipe[rstudio::cran]
      - recipe[rstudio::server]

    attributes:

  - name: users
    data_bags_path: "test/integration/default/data_bags"
    run_list:

      - recipe[rstudio::cran]
      - recipe[rstudio::nginx]
      - recipe[rstudio::server]
      - recipe[rstudio::users]

    attributes:
