language: ruby
services: 
  - docker
rvm:
    - 2.3.1
before_install:
  - gem update --system
  - gem --version
before_script:
    - bundle exec foodcritic -f any .
    - bundle exec rake
    - bundle exec kitchen verify default-ubuntu-18

